-- Phase 1 Mutual Aid runtime foundation schema only.
-- No payments, payouts, wallets, automatic approvals, request intake, or public aid access.
CREATE TABLE IF NOT EXISTS mutual_aid_funds (id INTEGER PRIMARY KEY, name VARCHAR(255) NOT NULL UNIQUE, status VARCHAR(128) NOT NULL DEFAULT 'Building Toward Activation', activation_threshold INTEGER NOT NULL DEFAULT 20000, current_balance INTEGER NOT NULL DEFAULT 0, available_balance INTEGER NOT NULL DEFAULT 0, reserved_balance INTEGER NOT NULL DEFAULT 0, currency VARCHAR(3) NOT NULL DEFAULT 'USD', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mutual_aid_contributions (id INTEGER PRIMARY KEY, fund_id INTEGER NOT NULL, contributor_user_id INTEGER, amount INTEGER NOT NULL DEFAULT 0, currency VARCHAR(3) NOT NULL DEFAULT 'USD', status VARCHAR(64) NOT NULL DEFAULT 'recorded', source_reference VARCHAR(255), metadata JSON NOT NULL DEFAULT '{}', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mutual_aid_requests (id INTEGER PRIMARY KEY, fund_id INTEGER NOT NULL, requester_user_id INTEGER, category VARCHAR(128) NOT NULL DEFAULT 'unclassified', amount_requested INTEGER NOT NULL DEFAULT 0, currency VARCHAR(3) NOT NULL DEFAULT 'USD', status VARCHAR(64) NOT NULL DEFAULT 'draft', narrative TEXT NOT NULL DEFAULT '', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mutual_aid_request_documents (id INTEGER PRIMARY KEY, request_id INTEGER NOT NULL, document_type VARCHAR(128) NOT NULL DEFAULT 'supporting', storage_key TEXT NOT NULL DEFAULT '', status VARCHAR(64) NOT NULL DEFAULT 'pending', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mutual_aid_reviews (id INTEGER PRIMARY KEY, request_id INTEGER NOT NULL, reviewer_user_id INTEGER, status VARCHAR(64) NOT NULL DEFAULT 'not_started', notes TEXT NOT NULL DEFAULT '', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mutual_aid_decisions (id INTEGER PRIMARY KEY, request_id INTEGER NOT NULL, decision VARCHAR(64) NOT NULL DEFAULT 'pending', decided_by_user_id INTEGER, amount_approved INTEGER NOT NULL DEFAULT 0, rationale TEXT NOT NULL DEFAULT '', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mutual_aid_disbursements (id INTEGER PRIMARY KEY, request_id INTEGER NOT NULL, recipient_user_id INTEGER, amount INTEGER NOT NULL DEFAULT 0, currency VARCHAR(3) NOT NULL DEFAULT 'USD', status VARCHAR(64) NOT NULL DEFAULT 'not_started', payment_reference VARCHAR(255), created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mutual_aid_policy_versions (id INTEGER PRIMARY KEY, version VARCHAR(64) NOT NULL UNIQUE, title VARCHAR(255) NOT NULL, body TEXT NOT NULL DEFAULT '', effective_at DATETIME, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mutual_aid_member_acceptances (id INTEGER PRIMARY KEY, user_id INTEGER, policy_version_id INTEGER NOT NULL, accepted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mutual_aid_audit_logs (id INTEGER PRIMARY KEY, actor_user_id INTEGER, entity_type VARCHAR(128) NOT NULL, entity_id INTEGER, action VARCHAR(128) NOT NULL, before JSON NOT NULL DEFAULT '{}', after JSON NOT NULL DEFAULT '{}', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mutual_aid_request_status_history (id INTEGER PRIMARY KEY, request_id INTEGER NOT NULL, from_status VARCHAR(64), to_status VARCHAR(64) NOT NULL, changed_by_user_id INTEGER, reason TEXT NOT NULL DEFAULT '', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mutual_aid_committee_members (id INTEGER PRIMARY KEY, user_id INTEGER, role VARCHAR(128) NOT NULL DEFAULT 'reviewer', status VARCHAR(64) NOT NULL DEFAULT 'inactive', appointed_at DATETIME, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mutual_aid_conflict_disclosures (id INTEGER PRIMARY KEY, request_id INTEGER, committee_member_id INTEGER, disclosure TEXT NOT NULL DEFAULT '', status VARCHAR(64) NOT NULL DEFAULT 'open', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mutual_aid_appeals (id INTEGER PRIMARY KEY, request_id INTEGER NOT NULL, appellant_user_id INTEGER, status VARCHAR(64) NOT NULL DEFAULT 'not_started', reason TEXT NOT NULL DEFAULT '', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mutual_aid_fraud_reviews (id INTEGER PRIMARY KEY, request_id INTEGER, status VARCHAR(64) NOT NULL DEFAULT 'not_started', risk_level VARCHAR(64) NOT NULL DEFAULT 'unknown', notes TEXT NOT NULL DEFAULT '', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mutual_aid_reconciliation_reports (id INTEGER PRIMARY KEY, fund_id INTEGER NOT NULL, period_start DATETIME, period_end DATETIME, status VARCHAR(64) NOT NULL DEFAULT 'draft', totals JSON NOT NULL DEFAULT '{}', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mutual_aid_category_budgets (id INTEGER PRIMARY KEY, fund_id INTEGER NOT NULL, category VARCHAR(128) NOT NULL, budget_amount INTEGER NOT NULL DEFAULT 0, reserved_amount INTEGER NOT NULL DEFAULT 0, currency VARCHAR(3) NOT NULL DEFAULT 'USD', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mutual_aid_vendor_recipients (id INTEGER PRIMARY KEY, name VARCHAR(255) NOT NULL, status VARCHAR(64) NOT NULL DEFAULT 'inactive', contact_metadata JSON NOT NULL DEFAULT '{}', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);

-- Phase 5 financial controls and administrative disbursement tracking only.
ALTER TABLE mutual_aid_funds ADD COLUMN reserve_percent INTEGER NOT NULL DEFAULT 10;
ALTER TABLE mutual_aid_funds ADD COLUMN approval_threshold INTEGER NOT NULL DEFAULT 500;
ALTER TABLE mutual_aid_disbursements ADD COLUMN receipt_required BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE mutual_aid_disbursements ADD COLUMN notes TEXT NOT NULL DEFAULT '';
ALTER TABLE mutual_aid_disbursements ADD COLUMN scheduled_for DATETIME;
ALTER TABLE mutual_aid_disbursements ADD COLUMN closed_at DATETIME;
ALTER TABLE mutual_aid_disbursements ADD COLUMN created_by_user_id INTEGER;
ALTER TABLE mutual_aid_disbursements ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
CREATE TABLE IF NOT EXISTS mutual_aid_disbursement_status_history (id INTEGER PRIMARY KEY, disbursement_id INTEGER NOT NULL, from_status VARCHAR(64), to_status VARCHAR(64) NOT NULL, changed_by_user_id INTEGER, reason TEXT NOT NULL DEFAULT '', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
