ROLE_KEYS = [
    "architect",
    "operator",
    "steward",
    "builder",
    "connector",
    "protector",
    "nurturer",
    "educator",
    "resourceGenerator",
]

ROLE_LABELS = {
    "architect": "Architect",
    "operator": "Operator",
    "steward": "Steward",
    "builder": "Builder",
    "connector": "Connector",
    "protector": "Protector",
    "nurturer": "Nurturer",
    "educator": "Educator",
    "resourceGenerator": "ResourceGenerator",
}

QUESTION_MAP: list[dict[str, float]] = [
    {"architect": 1.0, "operator": 0.6, "steward": 0.4},
    {"operator": 1.0, "builder": 0.6, "architect": 0.3},
    {"steward": 1.0, "protector": 0.6, "operator": 0.3},
    {"builder": 1.0, "operator": 0.5, "resourceGenerator": 0.2},
    {"connector": 1.0, "nurturer": 0.4, "educator": 0.3},
    {"protector": 1.0, "steward": 0.5, "architect": 0.3},
    {"nurturer": 1.0, "connector": 0.5, "steward": 0.2},
    {"educator": 1.0, "nurturer": 0.4, "architect": 0.2},
    {"resourceGenerator": 1.0, "builder": 0.4, "connector": 0.3},
    {"architect": 0.9, "protector": 0.4, "operator": 0.3},
    {"operator": 0.9, "steward": 0.4, "builder": 0.3},
    {"steward": 0.9, "nurturer": 0.3, "protector": 0.3},
    {"builder": 0.9, "resourceGenerator": 0.3, "architect": 0.2},
    {"connector": 0.9, "educator": 0.3, "nurturer": 0.3},
    {"protector": 0.9, "architect": 0.3, "steward": 0.3},
    {"nurturer": 0.9, "connector": 0.4, "educator": 0.3},
    {"educator": 0.9, "architect": 0.3, "connector": 0.2},
    {"resourceGenerator": 0.9, "connector": 0.3, "builder": 0.3},
    {"architect": 0.8, "steward": 0.3, "protector": 0.3},
    {"operator": 0.8, "architect": 0.3, "builder": 0.3},
    {"steward": 0.8, "operator": 0.3, "protector": 0.4},
    {"builder": 0.8, "operator": 0.3, "resourceGenerator": 0.3},
    {"connector": 0.8, "nurturer": 0.3, "educator": 0.3},
    {"protector": 0.8, "steward": 0.4, "operator": 0.2},
    {"nurturer": 0.8, "educator": 0.4, "connector": 0.2},
    {"educator": 0.8, "nurturer": 0.3, "architect": 0.2},
    {"resourceGenerator": 0.8, "builder": 0.4, "connector": 0.2},
    {"architect": 0.7, "resourceGenerator": 0.3, "operator": 0.2},
    {"operator": 0.7, "architect": 0.3, "steward": 0.3},
    {"educator": 0.7, "nurturer": 0.3, "connector": 0.3},
]
