import React, { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { getMyInstitutionalProfile, saveMyInstitutionalProfile } from "../api/societyBuilder";
import "../styles/societyBuilder.css";

const empty = { display_name:"", headline:"", primary_contribution:"", contribution_categories_json:[], availability:"", contribution_type:"Volunteer", looking_for_json:[], skills_to_learn_json:[], goals_json:[], needs_json:[], needs_privacy_level:"Care Team Only", current_projects_json:[], impact_summary_json:{}, visibility:"Society Members" };
const split = (v) => String(v || "").split("\n").map((x)=>x.trim()).filter(Boolean);
const join = (v) => (Array.isArray(v) ? v.join("\n") : "");

export default function SocietyInstitutionalProfilePage({ edit=false }){
  const { societyId } = useParams(); const nav = useNavigate();
  const [data,setData]=useState(null); const [form,setForm]=useState(empty); const [error,setError]=useState(""); const [msg,setMsg]=useState("");
  useEffect(()=>{getMyInstitutionalProfile(societyId).then((r)=>{setData(r); if(r.profile) setForm({...empty,...r.profile});}).catch(e=>setError(e.message));},[societyId]);
  const set=(k,v)=>setForm({...form,[k]:v});
  async function submit(e){e.preventDefault(); setError(""); setMsg(""); try{await saveMyInstitutionalProfile(societyId, form); setMsg("Institutional Profile saved."); nav(`/societies/${societyId}/profile`);}catch(err){setError(err.message)}}
  if(!data) return <main className="society-builder-shell"><p>Loading Institutional Profile...</p>{error&&<p className="society-warning">{error}</p>}</main>;
  if(!edit) return <main className="society-builder-shell"><p className="society-kicker">Institutional Profile</p><h1>{data.society.name}</h1><p>How will you help build this institution?</p><section className="society-grid"><article className="society-card"><h2>My Contribution</h2><p>{form.primary_contribution || "Not shared yet"}</p><p>{form.contribution_categories_json?.join(", ")}</p><p>{form.availability}</p></article><article className="society-card"><h2>How can this institution help you?</h2><p><strong>What I’m Looking For:</strong> {form.looking_for_json?.join(", ") || "Not shared yet"}</p><p><strong>Skills I’d Like To Learn:</strong> {form.skills_to_learn_json?.join(", ") || "Not shared yet"}</p><p><strong>My Goals:</strong> {form.goals_json?.join(", ") || "Not shared yet"}</p><p><strong>My Needs:</strong> saved with {form.needs_privacy_level || "Care Team Only"} privacy.</p></article><article className="society-card"><h2>I’m Organizing</h2><p>{form.current_projects_json?.join(", ") || "No current projects shared."}</p></article><article className="society-card"><h2>My Society Impact</h2><p>{Object.entries(form.impact_summary_json || {}).map(([k,v])=>`${k}: ${v}`).join(", ") || "Impact summary not shared yet."}</p></article></section><div className="society-actions"><Link className="society-btn" to={`/societies/${societyId}/profile/edit`}>Edit Institutional Profile</Link><Link className="society-btn secondary" to={`/societies/${societyId}/directory`}>Open Society Directory</Link></div></main>;
  return <main className="society-builder-shell"><p className="society-kicker">Institutional Profile</p><h1>How will you help build this institution?</h1><p>How can this institution help you?</p>{msg&&<p className="society-success">{msg}</p>}{error&&<p className="society-warning">{error}</p>}<form className="society-form" onSubmit={submit}><label>Display name<input value={form.display_name} onChange={e=>set("display_name",e.target.value)}/></label><label>Headline<input value={form.headline} onChange={e=>set("headline",e.target.value)}/></label><label>My Contribution<input value={form.primary_contribution} onChange={e=>set("primary_contribution",e.target.value)} required/></label><label>Contribution categories<select onChange={e=>set("contribution_categories_json", Array.from(new Set([...(form.contribution_categories_json||[]), e.target.value])).filter(Boolean))}><option value="">Add a suggested category</option>{data.presets.contribution_categories.map(c=><option key={c}>{c}</option>)}</select></label><p>{form.contribution_categories_json?.join(", ")}</p><label>My Availability<textarea value={form.availability} onChange={e=>set("availability",e.target.value)} /></label><label>Contribution Type<select value={form.contribution_type} onChange={e=>set("contribution_type",e.target.value)}>{["Volunteer","Paid Professional (show only if I choose)","Organizer","Sponsor","Custom"].map(x=><option key={x}>{x}</option>)}</select></label><label>What I’m Looking For<textarea value={join(form.looking_for_json)} onChange={e=>set("looking_for_json",split(e.target.value))}/></label><label>I’m Organizing<textarea value={join(form.current_projects_json)} onChange={e=>set("current_projects_json",split(e.target.value))}/></label><label>Skills I’d Like To Learn<textarea value={join(form.skills_to_learn_json)} onChange={e=>set("skills_to_learn_json",split(e.target.value))}/></label><label>My Needs<textarea value={join(form.needs_json)} onChange={e=>set("needs_json",split(e.target.value))}/></label><label>Needs privacy<select value={form.needs_privacy_level} onChange={e=>set("needs_privacy_level",e.target.value)}>{["Care Team Only","Admin Only","Private","Society Members"].map(x=><option key={x}>{x}</option>)}</select></label><label>My Goals<textarea value={join(form.goals_json)} onChange={e=>set("goals_json",split(e.target.value))}/></label><button className="society-btn">Save Institutional Profile</button></form></main>;
}
