import { readFileSync } from 'node:fs';

const component = readFileSync('src/components/IntelligenceHealthMonitor.jsx', 'utf8');
const css = readFileSync('src/styles/dashboard.css', 'utf8');
const checks = [
  ['Executive and Technical View use the same result source', /const result = safeObject\(diagnosticRunState \|\| history\[0\]\)/.test(component) && component.includes('viewMode === "executive"') && component.includes('viewMode === "technical"')],
  ['Diagnostic action buttons are visible and wired to handlers', component.includes('Run Full Intelligence Diagnostic') && component.includes('Generate Public Diagnostic Report') && /<button className="hero-btn" type="button" onClick=\{run\}/.test(component) && /<button className="hero-btn secondary" type="button" onClick=\{generateReport\}/.test(component)],
  ['Fallback data is not treated as a root-cause diagnostic result', /const firstFailureIndex = hasDiagnosticResult && hasActiveRegression \?/.test(component) && component.includes('const hasActiveRegression = regressionCount > 0;') && component.includes(': -1;')],
  ['Runtime verification requires downstream consumption', component.includes('downstream_consumption_observed') && /const isRuntimeVerified = \(evidence\).*downstream_consumption_observed/s.test(component)],
  ['Executive View cannot report Connected without runtime evidence', /if \(!isRuntimeVerified\(evidence\)\) return/.test(component) && !/return "Connected";\n};\n\nexport default/.test(component)],
  ['Pipeline highlights upstream, downstream, first failure, and blast radius', ['upstream', 'downstream', 'first-failure', 'blast-radius', 'firstFailureIndex', 'blastRadius'].every((token) => component.includes(token))],
  ['Mission Control health surfaces avoid placeholder health percentages', !/(45%|47%|71%|73%|75%|77%|78%|80%|90%\+|91%|92%|94%)/.test(component)],
  ['Ecosystem Command Center only renders diagnostic subsystems', /const ecosystemCommandSystems = asArray\(ecosystemIntelligence\.subsystems\);/.test(component) && !component.includes('Math.max(72, Number(healthScore)')],
  ['Mobile responsiveness covers tables and pipeline components', css.includes('@media (max-width: 700px)') && css.includes('.runtime-evidence-table') && css.includes('.mission-pipeline .pipeline-node')],
  ['Root Cause Evidence exposes the selection trace and View Evidence navigation', component.includes('root_cause_selection_trace') && component.includes('Root Cause Evidence') && component.includes('rootCauseTraceCandidates') && component.includes('selection_boolean_or_comparison') && component.includes('selected_layer_mismatches') && component.includes('no_mismatch_explanation') && component.includes('showRootCauseEvidence') && /View Evidence[\s\S]*showRootCauseEvidence/.test(component)],
  ['Zero-regression Mission Control avoids stale root-cause narrative', component.includes('No active regression selected') && component.includes('Clear remaining operational warnings') && component.includes('Verify release readiness') && component.includes('warningVerificationQueue') && /const rootCauseSummary = hasActiveRegression && rootCauseLayer/.test(component)],
  ['Executive metrics separate platform health, release readiness, production confidence, and risk', component.includes('deriveExecutiveRisk') && component.includes('deriveMissionStatus') && component.includes('const releaseReadiness = clampPercent') && component.includes('const productionConfidence = clampPercent') && component.includes('const executiveRisk = commandCenter.executive_risk') && component.includes('Platform Health') && component.includes('Release Readiness') && component.includes('Executive Risk')],
  ['AI Forecast projects both health and release readiness', component.includes('Projected health score') && component.includes('Projected release readiness') && component.includes('projected_release_readiness')],
  ['Production confidence is measured from diagnostics and evidence instead of a placeholder', !component.includes('Production confidence not measured') && !component.includes('production confidence not measured') && component.includes('verifiedReruns') && component.includes('deploymentEvidenceVerified') && component.includes('diagnosticsPassed')],
  ['Executive Operations generates objectives automatically', component.includes('const executiveObjectives = [') && component.includes("Today's Objectives") && component.includes('Raise Release Readiness from') && component.includes('Remove ${warningCount} operational warning')],
  ['Executive Operations generates an ordered work queue', component.includes('const executiveWorkQueue = priorityQueue') && component.includes('Executive Work Queue') && component.includes('businessValue') && component.includes('estimatedTime') && component.includes('expectedMetricImprovement') && component.includes('responsibleLayer')],
  ['Executive Operations calculates release gates and approval logic', component.includes('const deploymentGates = [') && component.includes('Regression Gate') && component.includes('Verification Gate') && component.includes('Baseline Gate') && component.includes('Warning Gate') && component.includes('Evidence Gate') && component.includes('const releaseApproved = deploymentGates.every') && component.includes('Release Approval')],
  ['Executive Operations projects metrics without changing diagnostic scoring', component.includes('const projectedPlatformHealth = clampPercent') && component.includes('const projectedReleaseReadiness = clampPercent') && component.includes('const projectedProductionConfidence = clampPercent') && component.includes('Success Projection')],
  ['Executive briefing narrative stays consistent with gates and projections', component.includes('const executiveOperationsNarrative =') && component.includes('The institution is') && component.includes('Completing today\'s objectives is projected to improve Release Readiness') && component.includes('AI COO Narrative')],

  ['Executive Decision generation is available for every work queue item', component.includes('const executiveDecisionCards = executiveWorkQueue.map') && component.includes('Executive Decision Engine') && component.includes('Risk if Deferred') && component.includes('Decision Type') && component.includes('Open Member Intelligence') && component.includes('Launch Verification')],
  ['Executive Resource Allocation is automatically prioritized', component.includes('const executiveResourceAllocation = [') && component.includes('Executive Resource Allocation') && component.includes('High ROI') && component.includes('Platform Intelligence')],
  ['Decision simulation covers completed, delayed, and ignored scenarios', component.includes('const decisionSimulation = [') && component.includes('If completed today') && component.includes('If delayed') && component.includes('If ignored for 7 days') && component.includes('Decision Simulation')],
  ['Institution Health calculations produce executive KPIs', component.includes('const institutionHealthIndex = [') && component.includes('Technology Health') && component.includes('Knowledge Health') && component.includes('Leadership Health') && component.includes('Overall Institutional Health')],
  ['Strategic objective generation separates objective levels', component.includes('const strategicObjectiveGroups = {') && component.includes('Operational Objectives') && component.includes('Strategic Objectives') && component.includes('Institutional Objectives')],
  ['Executive memory tracks completed and delayed objectives', component.includes('const executiveMemory = {') && component.includes('Completed Today') && component.includes('Completed This Week') && component.includes('Completed This Month') && component.includes('Repeated Objectives') && component.includes('Frequently Delayed Objectives')],
  ['Institution impact summaries cover systems, members, deployment, revenue, knowledge, community, and institution', component.includes('const impactForWorkItem =') && component.includes('systemsAffected') && component.includes('membersAffected') && component.includes('deploymentImpact') && component.includes('revenueImpact') && component.includes('knowledgeImpact') && component.includes('communityImpact') && component.includes('institutionImpact')],
  ['Executive narrative reads like an adaptive COO briefing', component.includes('operationally stable') && component.includes('Executive attention should focus on') && component.includes('Business systems remain') && component.includes('deployment gates require additional evidence')],
  ['Executive timeline tracks operations stages while preserving historical labels', component.includes('const executiveOperationsTimeline = ["Diagnostic", "Verification", "Evidence", "Executive Review", "Release Approval", "Deployment"]') && component.includes('Historical: {event.historicalLabel}')],
];
let failed = false;
for (const [name, pass] of checks) {
  console.log(`${pass ? 'PASS' : 'FAIL'} ${name}`);
  if (!pass) failed = true;
}
if (failed) process.exit(1);
